app_addFriend/urls.py
from django.conf.urls import url
from .views import index, add_friend, unfriend

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    url(r'^unfriend/(?P<id>\d+)/$', unfriend, name='unfriend'),
]

app_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

app_update/urls.py
from django.conf.urls import url
from .views import welcome_page, index, add_status, delete_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^welcome_page', welcome_page, name='welcome_page'),
    url(r'^delete_status/(?P<id>\d+)/$', delete_status, name='delete_status'),
]

twita/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import app_update.urls as index_update
import app_profile.urls as index_profile
import app_addFriend.urls as index_addfriend
import app_stats.urls as index_stats
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/update/welcome_page', permanent=False), name='index'),
    url(r'update/', include(index_update, namespace='update')),
    url(r'profile/', include(index_profile, namespace='profile')),
    url(r'add/', include(index_addfriend, namespace='add')),
    url(r'stats/', include(index_stats, namespace='stats')),
]

app_addFriend/models.py
from django.db import models

class Friends(models.Model):
    name = models.CharField(max_length=27)
    url = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

app_profile/models.py
from django.db import models

class Biodata(models.Model):
    name = models.CharField(max_length=27)
    email = models.EmailField()
    birthdate = models.DateField()
    gender = models.CharField(max_length=6)
    expertise = models.TextField()
    description = models.TextField()

app_stats/models.py
from django.db import models

# Create your models here.

app_update/models.py
from django.db import models

class Status(models.Model):
    isi = models.CharField(max_length=140, default="...")
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']

app_addFriend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'What\'s your friend\'s name?',
        'size':140
    }
    url_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'What\'s your friend\'s URL?',
        'size':140
    }

    name = forms.CharField(label='Name', required=True, max_length=100, widget=forms.TextInput(attrs=name_attrs))
    url = forms.URLField(label='URL', required=True, widget=forms.TextInput(attrs=url_attrs))

app_update/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Tolong dong isi :c',
    }
    isi_attrs = {
        'type': 'text',
        'cols':155,
        'rows':6,
        'class': 'form-control',
        'placeholder':'What\'s on your mind ?',
        'style':'resize:none;'
    }

    isi = forms.CharField(label='', required=True, max_length=140, widget=forms.Textarea(attrs=isi_attrs))
    

app_addFriend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError
from django import forms
from .forms import Add_Friend_Form
from .models import Friends
from django.contrib import messages

response = {}
def index(request):
    allFriends = Friends.objects.all()
    response['allFriends'] = allFriends
    response['add_friend_form'] = Add_Friend_Form
    return render(request, 'friend.html', response)

def add_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        if validate_url(request.POST['url']):
            response['url'] = request.POST['url']
            friend = Friends(name=response['name'],url=response['url'])
            friend.save()
            messages.success(request, 'Welcome your new friend!')
        else:
            messages.warning(request, 'Are you sure that is your friend\'s URL? Try again!')
        return HttpResponseRedirect('/add/')
    else:
        messages.warning(request, 'Are you sure that is your friend\'s URL? Try again!')
        return HttpResponseRedirect('/add/')

def validate_url(url):
    validate = URLValidator()
    try:
        validate(url)
    except ValidationError:
        return False
    return True

def unfriend(request,id):
    friend = Friends.objects.get(id=id)
    friend.delete()
    return HttpResponseRedirect('/add/')

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Biodata

response = {}
def index(request):
    profile = Biodata.objects.get(pk=1)
    split_expertise = profile.expertise.split(',')
    response['profile'] = profile
    response['split_expertise'] = split_expertise
    return render(request, 'profile.html', response)

app_stats/views.py
from django.shortcuts import render
from app_addFriend.models import Friends
from app_update.models import Status

img_url = "https://pbs.twimg.com/media/DLzIgLLUIAATlZY.png:large"
response = {}

def index(request):
    jumlah_teman = Friends.objects.all().count()
    jumlah_stats = Status.objects.all().count()
    latest_stats = Status.objects.first()
    response['jumlah_teman'] = jumlah_teman
    response['jumlah_stats'] = jumlah_stats
    response['latest_stats'] = latest_stats
    response['img_url'] = img_url
    return render(request, 'stats.html', response)

    

app_update/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status
#from app_profile.views import img_url
img_url = "https://pbs.twimg.com/media/DLzIgLLUIAATlZY.png:large"

# Create your views here.
response = {}
def welcome_page(request):
    return render(request,'welcome_page.html',response)

def index(request):
    response['author'] = "Helvetica Standard"
    status = Status.objects.all()
    response['status'] = status
    response['img_url'] = img_url
    html = 'update.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == "POST" and form.is_valid()):
        response['isi'] = request.POST['isi']
        status = Status(isi = response['isi'])
        status.save()
        return HttpResponseRedirect('/update/')
    else:
        return HttpResponseRedirect('/update/')

def delete_status(request,id):
    status = Status.objects.get(id=id)
    status.delete()
    return HttpResponseRedirect('/update/')

app_addFriend/templates/friend.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href = "{% static 'css/style_addFriend.css' %}"/>
</head>
<body>
<section name="input-list" id="input-list">
    <div class="container">
        <br>
        <h2><img src="https://cdn4.iconfinder.com/data/icons/eldorado-user/40/add_friend-512.png"/ style="width:4.5rem; padding-right: 1rem;"><strong>Add Friend</strong></h2>
        <form id="form" method="POST" action="{% url 'add:add_friend' %}">
            {% csrf_token %}
            <table>
            {% for form in add_friend_form %}
                <tr>
                    <td width="8%" style="padding-top: 0.5rem;">
                        {{ form.label_tag }}
                    </td>
                    <td width="92%">
                        {{ form }}
                    </td>
                </tr>
            {% endfor %}
            </table>
            {% if messages %}
                <div class="messages" style="color: red;text-align: center;">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
            <input id="submit" type="submit" class="btn btn-md btn-block btn-primary" value="Add Friend" style="text-align: center; margin-top: 0.7rem; font-size: 110%;">
            <br>
        </form>
    </div>
</section>
<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">List friend</h2>
        <br>
        <div class="flex">
            {% if allFriends %}
                {% for data in allFriends %}
                    <div class="card effect__hover">
                        <div class="card__front">
                            <div class="to-do-list-name">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                Since {{data.created_date}}
                            </div>
                            <br>
                            <img src="http://icons.iconarchive.com/icons/icons8/windows-8/512/Cinema-Ninja-Turtle-icon.png" style="width: 4rem; height:4rem;border-radius: 50%;"/>
                            <hr>
                        </div>
                        <div class="card__back">
                            <br>
                            <img id="walking-turtle" src="https://png.icons8.com/windows/1600/0063B1/turtle" style="width: 4rem; height:4rem;border-radius: 50%;"/>
                            <div class="to-do-list-url">
                                <a href="{{data.url}}" target="_blank"><button class="btn btn-md btn-primary" id="visit">Visit your friend</button></a>
                            </div>
                            <div class="to-do-list-delete">
                               <a href="{% url 'add:index' %}unfriend/{{data.id}}"> <button class="btn btn-md btn-danger" id="delete" data-id="{{data.id}}">Unfriend</button></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Jomblo!</strong> Cari teman dong!
            </div>
            {% endif %}
        </div>
    </div>
</section>

</body>
{% endblock %}

app_profile/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<head>
  <link rel="stylesheet" type="text/css" href = "{% static 'css/style_profile.css' %}"/>
</head>
<div class="container">
  <br>
  <h2><img src="https://pbs.twimg.com/media/DL8YAVCUEAAfNHl.png:large"/ style="width:4.5rem; padding-right: 1rem;"><strong>Profile</strong></h2>
  <br>
  <p/><img src="https://media.tenor.com/images/69a94edcadf2ca7eab1d082441a004d4/tenor.gif" style="width:20rem;"/></p>
  <h3><center><img src="http://simpleicon.com/wp-content/uploads/user1.png" style="width:2rem;"/> {{ profile.name }} </center></h3><br>
<div class="to-do-list">
  <table class="table">
    <tr>
      <td><img src="https://pbs.twimg.com/media/DL8hzMUV4AAOsPq.png:large" style="width:2rem;"/></td>
      <td><h5>Birthday</h5></td>
      <td><h6>{{ profile.birthdate }}</h6></td>
    </tr>
    <tr>
      <td><img src="https://pbs.twimg.com/media/DL8h_CvU8AEF6xg.png:large" style="width:2rem;"/></td>
      <td><h5>Gender </h5></td>
      <td><h6>{{ profile.gender }}</td></h6>
    </tr>
    <tr>
      <td><img src="https://pbs.twimg.com/media/DL8iJnkVAAADCM9.png:large" style="width:2rem; padding-top: 0.5rem;"/></td>
      <td id="expert"><h5> Expertise </h5></td>
      <td>
        <table>
          <tr>
            {%for experts in split_expertise%}
              <td><h6><span class="expertise">{{ experts }}</span></h6></td>
            {%endfor%}
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><img src="https://pbs.twimg.com/media/DL8idbQU8AE5cgC.png:large" style="width:2rem;"/></td>
      <td><h5>Description </h5></td>
      <td><h6>{{ profile.description }}</h6></td>
    </tr>
    <tr>
      <td><img src="https://maxcdn.icons8.com/Share/icon/nolan/User_Interface//email1600.png" style="width:2rem;"/></td>
      <td><h5>Email </h5></td>
      <td><h6>{{ profile.email }}</h6></td>
    </tr>
  </table>
</div>
</div>
{% endblock %}

app_stats/templates/stats.html
{% extends "base.html" %} {% block content %}
{% load static %}

<head>
    <link rel="stylesheet" type="text/css" href = "{% static 'css/style_stats.css' %}"/>
</head>

<br>

<section name="stats" id="stats">
  <h2><img src="https://image.flaticon.com/icons/png/512/39/39915.png" style="width:3.5rem; padding-right: 1rem; padding-bottom: 0.7rem;"><strong>Statistics</strong></h2>
    <div class="contain-numbers">
        <div class="container friends">
            <img class="img-normal" src="{{img_url}}"/>
        </div>
        <div class="container feeds">
            <h2 class="title-stats" style="text-align: left; font-size:35px">Kura-Kura Company</h2><br>
            <div class="description" style="font-size:35px">
                <strong>Friends</strong> {{ jumlah_teman }} People
                <br>
                <strong>Feed</strong> {{ jumlah_stats }} Post
            </div>
        </div>
    </div>
</section>

<!-- <div class="haha"> -->
    <div class="text-head">Latest post</div>
    <div class="container">
            {% if latest_stats %}
                    <div class="flex-item">
                        <div class="status-list">
                            <p> <img class=top src={{img_url}} style="width:3rem; height:3rem;"/> <strong style="color:black"> Kura-Kura Company </strong></p>
                                <br>

                            <div class="isi-status">
                                {{latest_stats.isi}}
                            </div>
                            <div class="date-added">
                                {{latest_stats.created_date}}
                            </div>
                        </div>
                    </div>
                    </br>

            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Takde status.
            </div>
            {% endif %}
    </div>
<!-- <div> -->
{% endblock %}

app_update/templates/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href = "{% static 'css/style_appupdate.css' %}"/>
</head>


<body>
<section name="input-list" id="input-list">
	<div class="container2" >
		<form id="form" method="POST" action="{% url 'update:add_status' %}">
			<br>
            <h2><img src="http://findicons.com/files/icons/1580/devine_icons_part_2/512/defult_doc.png"/ style="width:4.5rem; padding-right: 1rem;"><strong>Update Status</strong></h2>
            </br>
			{% csrf_token %}
			{{ status_form }}
			</br>
			<input type="submit" class="btn-custom button btn btn-md btn-block btn-primary " value="Post" id="submit-custom">
		</form>
	</div>
</section>

</br>
    <div class="container">

            {% if status %}
                {% for data in status %}
                    <div class="flex-item">
                        <div class="status-list">
                            <p> <img class=top src={{img_url}} style="width:3rem; height:3rem;"/> <strong> Kura-Kura Company </strong></p>
                                <br>

                            <div class="isi-status">
                                {{data.isi}}
                            </div>
                            <div class="date-added">
                                {{data.created_date}}
                            </div>
                            <div class="delete-status">
                               <a href="{% url 'update:index' %}delete_status/{{data.id}}"> <button class="btn btn-md btn-danger" id="delete" data-id="{{data.id}}">Delete</button></a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Takde status.
            </div>
            {% endif %}

    </div>

</section>
</body>

{% endblock %}

app_update/templates/welcome_page.html
{% load static %}

</style>
<head>
	<title>Tuita</title>
	<link rel="stylesheet" type="text/css" href = "{% static 'css/style_welcomepage.css' %}"/>
</head>
<body>
	<div class="title_container">
		<br>
		<img src="https://pbs.twimg.com/media/DL69a0VVwAANUFn.png:large", width="300", height="300">
		<!-- <h1>Tuitaa</h1> -->
	</div>
	<br> <br> <br>
	<div class="container">
		<h1>Welcome back, Turtles!</h1>
		<img src="https://pbs.twimg.com/media/DLzIgLLUIAATlZY.png:large" style="width:20rem;"/>
		<div class="spinner">
		<div class="cube1"></div>
		<div class="cube2"></div>
		</div>
	</div>
	<br>

</body>

<meta http-equiv="refresh" content="4.5;url=/update/"/>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tuita</title>
    <link rel="icon" href="https://pbs.twimg.com/media/DLn1mnTUMAAizTh.png:large">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />
</head>
<style>
#navbarNav li img {
    margin-right: 1.5rem;
}
#navbarNav li b {
    font-family: Raleway;
    color: black;
    padding-top: 15px;
    margin-right: 1.5rem;
    display: none;
}
#navbarNav a:hover {
    color: #fff;
}
#navbarNav a:hover img {
    display: none;
}
#navbarNav a:hover b {
    display: block;
    padding: 10px;
    border-radius: 5px;
}
.subject{
    font-size: 20px;
    font-family: Raleway;
    color: #6650ff;
}
.value{
    font-size: 20px;
    font-family: Raleway;
    color: #ff102c;
}
.footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  /* Set the fixed height of the footer here */
  height: 60px;
  line-height: 60px; /* Vertically center the text there */
  background-color: #f5f5f5;
}
header{
    margin-top: 75px;
}

</style>
<body style="background-color: #EBEBCB">
    <header>
        {% include "header.html" %}
    </header>
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
    <footer class = "footer">
        {% include "footer.html" %}
    </footer>
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/footer.html
<style type="text/css">
    html {
        position: relative;
        min-height: 100%;
    }

    body {
        /* Margin bottom by footer height */
        margin-bottom: 100px;
    }

    .footer {

        position: absolute;
        bottom: 0;
        width: 100%;
        /* Set the fixed height of the footer here */
        height: 70px;
        line-height: 60px;
        /* Vertically center the text there */
        background-color: #9EA5A5;
        color: #ffffff;
    }

    .resize-container {
        position: relative;
        display: inline-block;
        cursor: move;
        margin: 0 auto;
    }

    .resize-container img {
        display: block
    }

    .resize-container:hover img,
    .resize-container:active img {
        outline: 2px dashed rgba(222, 60, 80, .9);
    }
</style>

<div class="container" style="text-align: center;">
    <span>Made with <span style="color: #fd0864">Love</span> and <span style="color: #fff000">Sad</span> by <span style="color: #33FF00">KuraKura</span>
    </span>
</div>

templates/header.html
<style>
    .container-fullwidth{
      position: fixed;
      top: 0;
      width: 100%;
      z-index: 1000;
    }
</style>

<div class="container-fullwidth" style="color: black">
    <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/update/"><img src="https://pbs.twimg.com/media/DLzMU4-VAAAdrpL.jpg:large" width="100"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/update/"><img src="https://cdn2.iconfinder.com/data/icons/the-shine-of-small-things/128/shining_mix_document-128.png" width="50" height="50"><b>Update</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/profile/"><img src="https://cdn3.iconfinder.com/data/icons/tango-icon-library/48/go-home-128.png" width="50" height="50"><b>Profile</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/add/"><img src="https://cdn2.iconfinder.com/data/icons/facebook-svg-icons-1/64/friend_finder-128.png" width="50" height="50"><b>Friends</b></a>
          </li>
          <li class="nav-item">
            <a class="nav-link"  href="/stats/"><img src="https://cdn4.iconfinder.com/data/icons/general-office/91/General_Office_18-128.png" width="50" height="50"><b>Stats</b></a>
          </li>
        </ul>
      </div>
    </nav>
</div>